version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/backend/
hooks:
  # BeforeInstall:
  #   - location: backend/scripts/clean_instance.sh
  #     timeout: 6000
  #     runas: root
  AfterInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 6000
      runas: root
    # - location: backend/scripts/django_commands.sh
    #   timeout: 6000
    #   runas: bitnami