# Generated by Django 3.0.6 on 2020-11-13 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('view_count', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('is_hide', models.BooleanField(default=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품 목록',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='순서')),
                ('volumn', models.CharField(max_length=50, verbose_name='용량')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'verbose_name': '상품 옵션',
                'verbose_name_plural': '상품 옵션 목록',
                'unique_together': {('product', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_category', models.CharField(choices=[('garden', '야채류'), ('green', '청과류'), ('grain', '곡류'), ('nuts', '견과류'), ('mushrooms', '버섯류'), ('etc', '기타/가공품')], max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '상품 분류',
                'verbose_name_plural': '상품 분류 목록',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='평가점수')),
                ('text', models.CharField(max_length=300, verbose_name='리뷰 내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 리뷰',
                'verbose_name_plural': '상품 리뷰 목록',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(verbose_name='수량')),
                ('amount', models.PositiveIntegerField(verbose_name='결제 총액')),
                ('payment_type', models.CharField(choices=[('card', '카드 결제'), ('cash', '무통장 입금')], max_length=10, verbose_name='결제수단')),
                ('status', models.IntegerField(choices=[(10, '결제 대기'), (20, '결제 완료'), (30, '배송 중 '), (40, '배송 완료 '), (50, '취소')], default=10, verbose_name='상태')),
                ('imp_id', models.CharField(blank=True, max_length=120, null=True)),
                ('merchant_id', models.CharField(max_length=120, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProductOption', verbose_name='구매 옵션')),
            ],
            options={
                'verbose_name': '구매내역',
                'verbose_name_plural': '구매내역 목록',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', '판매자'), ('B', '구매자')], default='B', max_length=5)),
                ('name', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('address_detail', models.CharField(max_length=100)),
                ('career', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, to='api.Product')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필 목록',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SmallCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='순서')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지 목록',
                'unique_together': {('product', 'order')},
            },
        ),
    ]
