# Generated by Django 3.0.6 on 2020-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201116_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
