# Generated by Django 3.0.6 on 2020-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201119_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
