# Generated by Django 3.0.6 on 2020-11-19 06:17

import api.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201119_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to=api.models.user_directory_path),
            preserve_default=False,
        ),
    ]
