# Generated by Django 3.0.6 on 2020-11-19 10:33

import api.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201119_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=api.models.user_directory_path),
        ),
    ]
