# Generated by Django 3.0.6 on 2020-11-23 03:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('top', '상단 대표 이미지'), ('content', '상품 설명 이미지')], default='top', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=api.models.user_directory_path),
        ),
    ]
