# Generated by Django 3.0.6 on 2020-11-23 12:31

import api.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201123_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=api.models.product_directory_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=api.models.productimage_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'image_type', 'order')},
        ),
        migrations.CreateModel(
            name='ProductQnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='순서')),
                ('question', models.CharField(max_length=100, verbose_name='질문')),
                ('answer', models.CharField(max_length=100, verbose_name='대답')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
            options={
                'verbose_name': '상품 문답',
                'verbose_name_plural': '상품 문답 목록',
                'unique_together': {('product', 'order')},
            },
        ),
    ]
