# Generated by Django 3.0.6 on 2020-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aptitude_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
