# Generated by Django 3.0.6 on 2020-11-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_aptitude_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='merchant_id',
            new_name='merchant_uid',
        ),
    ]
