# Generated by Django 3.0.6 on 2020-11-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201124_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_cabon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_pesticide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='natural',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pesticide_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='same_day_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
