# Generated by Django 3.0.6 on 2020-11-30 08:17

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20201130_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductQnA',
            new_name='ProductFaq',
        ),
        migrations.AlterField(
            model_name='product',
            name='address',
            field=models.CharField(max_length=200, verbose_name='농지 주소'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SmallCategory', verbose_name='상품 분류'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, verbose_name='상품 설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='무료 배송'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_cabon',
            field=models.BooleanField(default=False, verbose_name='저탄소'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_pesticide',
            field=models.BooleanField(default=False, verbose_name='저농약'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='natural',
            field=models.BooleanField(default=False, verbose_name='자연산'),
        ),
        migrations.AlterField(
            model_name='product',
            name='organic',
            field=models.BooleanField(default=False, verbose_name='유기농'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pesticide_free',
            field=models.BooleanField(default=False, verbose_name='무농약'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='same_day_shipping',
            field=models.BooleanField(default=False, verbose_name='당일 발송'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='판매자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=api.models.product_directory_path, verbose_name='대표 섬네일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
